### ISSUE TITLE
TypeError: __cinit__() takes at least 2 positional arguments (0 given)

### ISSUE THREAD

**Issue by trra1988** [THUwangcy/ReChorus#17]
========================================
cuda available: True
# cuda devices: 1
Load corpus from ../data/Grocery_and_Gourmet_Food/BaseReader.pkl
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main()
  File "main.py", line 56, in main
    corpus = pickle.load(open(corpus_path, 'rb'))
  File "pandas/_libs/internals.pyx", line 572, in pandas._libs.internals.BlockManager.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (0 given)

This Error shows when I run the code, is the problem with input? Thanks for reply

**Comment by trra1988** [comment]
it solved thanks
